intention_keys:

  # 其他工作室关键词
  studio_key:
    - "其他工作室"
    - "红岩"
    - "蓝山"

  # 本工作室相关
  qff_key:
    - "我们工作室"
    - "勤奋蜂"
    - "咱们工作室"

  # 本工作室的零基础关键词
  qff_freshmen_key:
    - "零基础"
    - "没有基础"
    - "没学过"
    - "好难"

  # 本工作室刷人关键词
  qff_stay_key:
    - "刷人"
    - "留几个人"

  # 本工作室的招新类问题关键词
  qff_recruit_key:
    - "招新"
    - "介绍"

  # 本工作室关于学长学姐的关键词
  qff_senior_stu_key:
    - "学长"
    - "学姐"
    - "dalao"
    - "大佬"

  # 关于学校的问题关键词
  school_key:
    - "我们学校"
    - "重邮"
    - "重庆邮电大学"
    - "这学校"

  # 感情倾向关键词
  like_key:
    - "贴贴"
    - "tql"
    - "好强"