#解决qff+school+like+three相关的回答

#涉及其他工作室
studio:
  - "别的俺不知道，但是学校确实有很多优秀的工作室捏"
  - "少讨论写别的嘛，学技术才是硬道理"
  - "俺书读的少，不敢乱说话"

qff:
  - "还是不太明白欸，你可以尝试这样问我:%0a咱们工作室会不会刷人？%0a零基础有关系吗？%0a勤奋蜂招新%0a咱们工作室学长学姐的博客"
  - "想问啥问题，可以说得细致一点嘛"
  - "欸，数据太少了(开发太菜了)，找不到确定的答案"

# 零基础
freshmen:
  - "没关系，很多学长也都是大一才入门，大二的化得再努力努力"
  - "莫慌嘛，开发大大啥技术我还是知道的，你多学几分钟就能超过他"
  - "努力才是硬道理！多花时间，卷起来！也可以问问各个部门的dalao们哦"

# 会不会刷人
stay:
  - "据可靠消息(小声bb)，咱不刷人，但是得认真完成每个阶段的学习才能跟得上哦"
  - "肯定是不刷的拉"
  - "加入咱的主要目的就是学习技术，一直努力就行(不刷人qwq)"

# 招新方面的问题
recruit:
  - "群公告里边都有哦"
  - "之前有发公告的,快去看看"

# 学长学姐的问题
senior:
  - "咱原来记得一些学长学姐的博客的，开发不让我说，欸"
  - "学长学姐都是大佬呢(除了某一个水鬼)"
  - "我是来划水的，问问他们让我也学一学赛"

#学校
school:
  - "咱学校也不算差，既来之则安之嘛"
  - "问问群友叭，这方面我都没了解过欸"
  - "emmm"

#情感
like:
  - "打咩嘚寺内"
  - "(羞)qwq"
  - "我没对象()"

#3G芯片
3G:
  - "咱当然知道：%0a2005年10月9日下午2:30，重庆市人民政府新闻办公室在重庆市新闻发布中心举行了新闻发布会。会议郑重发布了“世界第一颗0.13微米工艺的TD-SCDMA的3G手机核心芯片在重庆诞生”这一令国人自豪和骄傲的重大喜讯。重庆市人民政府新闻办和重庆邮电学院在此间联合宣布：具有我国自主知识产权的世界首枚“通芯一号”3G手机核心芯片已由重庆重邮信科股份有限公司（简称重邮信科）研发成功，并向媒体人士展示亮相。%0a这是世界上第一枚0.13微米工艺的TD-SCDMA的3G手机基带芯片。它的诞生，标志着我国3G通信核心芯片等关键技术已达到了世界领先水平。实现了从“中国制造”到“中国创造”的跨越。"